# Generated by Django 2.2.1 on 2019-06-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_connection_active_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
