# Generated by Django 2.2.1 on 2019-06-22 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('NEWORDER', 'NEWORD')], default='NEWORD', max_length=7)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('payload', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
    ]
