# Generated by Django 2.2.1 on 2019-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190622_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('NEWORD', 'New Order'), ('ABCART', 'Abandoned cart')], default='NEWORD', max_length=7),
        ),
    ]
