# Generated by Django 2.2.4 on 2019-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190626_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('NEWORD', 'New Order'), ('ABCART', 'Abandoned cart'), ('SUBNL', 'Subscribe newsletter')], default='NEWORD', max_length=7),
        ),
    ]
