# Generated by Django 2.2.9 on 2020-01-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191129_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_type',
            field=models.CharField(choices=[('AC', 'Active Campaign'), ('MC', 'MailChimp')], default='AC', max_length=2),
        ),
    ]
